// Generated by scripts/generate-blog-index.mjs. Do not edit manually.
import Blog0, { frontmatter as frontmatter0 } from "./0/blog.mdx";
import Blog1, { frontmatter as frontmatter1 } from "./1/blog.mdx";
import Blog2, { frontmatter as frontmatter2 } from "./2/blog.mdx";
import type { BlogEntry, BlogFrontmatter } from "../../typeDefs/blog";

const entry = (frontmatter: BlogFrontmatter, Content: BlogEntry["Content"]): BlogEntry => ({
  frontmatter,
  Content,
});

export const blogEntries = [
  entry(frontmatter0, Blog0),
  entry(frontmatter1, Blog1),
  entry(frontmatter2, Blog2),
].sort((a, b) => Date.parse(b.frontmatter.date) - Date.parse(a.frontmatter.date));

export const blogSummaries = blogEntries.map(({ frontmatter }) => frontmatter);

export function getBlog(slug: string) {
  return blogEntries.find(({ frontmatter }) => frontmatter.slug === slug);
}
